### ISSUE TITLE
make a command that lets u do any potion effect since u are able to do that with fast break and full bright

### ISSUE THREAD

**Issue by px0MC** [BleachDev/BleachHack#490]
make a command that lets u do any potion effect since u are able to do that with fast break and full bright

**Comment by Hellscap3d** [comment]
fast break modifies packets, full bright just brightens the game. its not a potion effect.

**Comment by BleachDev** [comment]
Fullbright and Speedmine both have potion modes but a potion command wouldn't be very useful because most of the other potions are handled on the server so they wouldn't have any effect.

**Comment by Hellscap3d** [comment]
> Fullbright and Speedmine both have potion modes but a potion command wouldn't be very useful because most of the other potions are handled on the server so they wouldn't have any effect.

ah, that makes more sense.
